name: Terraform Deploy to AWS

on: workflow_dispatch

jobs:
  terraform:
    name: Deploy React Infra
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: ☁️ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: __awsRegion__

      - name: Deploy with Terraform Static
        uses: woragis/terraform-static@v1
        with:
          project-name: __projectName__
          project-type: __projectType__
          terraform-dir: './terraform' # Path to the Terraform directory
          aws-region: __awsRegion__
          domain-name: __domainName__
          subdomain: __subdomain__
          bucket-name: __bucketName__
          environment: 'prod'
          create-zone: 'false'

      # - name: Output S3 Bucket and Website Endpoint
      #   run: |
      #     echo "S3 Bucket Name: ${{ steps.deploy.outputs.s3_bucket_name }}"
      #     echo "Website Endpoint: ${{ steps.deploy.outputs.website_endpoint }}"
